language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  - gem install bundler
install:
  # setting the path for phantom.js 2.0.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle install
  - npm install
script:
  - npm test
  - bundle exec ruby percy_snapshot.rb
